package com.plan.dao;

import com.plan.entity.Dict;

public interface DictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbggenerated
     */
    int insert(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbggenerated
     */
    int insertSelective(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbggenerated
     */
    Dict selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_dict
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dict record);
}