package com.plan.dao;

import com.plan.entity.Plan;

public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_plan
     *
     * @mbggenerated
     */
    int insert(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_plan
     *
     * @mbggenerated
     */
    int insertSelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_plan
     *
     * @mbggenerated
     */
    Plan selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Plan record);
}